modLoader = "javafml"
loaderVersion = "[26,)"
license = "All Rights Reserved"
[[mods]]
modId = "buildscape"
version = "1.0.0"
displayName = "Buildscape"
displayURL = "buildscape.online"
authors = "Kingodogo"
description = '''Welcome to Buildscape the ultimate expansion for builders, architects, and creators!'''
[[dependencies.buildscape]]
    modId="neoforge"
    mandatory=true
    versionRange="[26,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.buildscape]]
    modId="minecraft"
    mandatory=true
    versionRange="[26,)"
    ordering="AFTER"
    side = "BOTH"

[[mixins]]
config = "buildscape.mixins.json"

