modLoader = "javafml"
loaderVersion = "[40,)"
license = "All Rights Reserved"
[[mods]]
modId = "buildscape"
version = "3.0.2-VH"
displayName = "BuildScape"
displayURL = "buildscape.online"
logoFile = "buildscape.png"
authors = "Kingodogo"

description = '''Welcome to Buildscape the ultimate expansion for builders, architects, and creators! This mod adds a massive collection of new building blocks designed to spark creativity and transform your Minecraft world into a true masterpiece. From sleek modern tiles and rustic wood planks to glowing crystals, smooth marbles, and industrial metals Buildscape gives you every texture and color you could imagine. Whether you're crafting a cozy village, a grand castle, or a futuristic city, these blocks fit perfectly into any theme or building style. Each block has been carefully designed to blend seamlessly with vanilla Minecraft while adding fresh, unique flair to your builds. Experiment with countless combinations, mix materials, and design without limits.'''

[[dependencies.buildscape]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.buildscape]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="AFTER"
    side = "BOTH"

