plugins {
    id 'java'
}

configurations { commonVariant }
dependencies {
    commonVariant project(path: ':common', configuration: 'v118xElements')
    implementation project(path: ':common', configuration: 'v118xElements')
}

tasks.named('jar', Jar) {
    from configurations.commonVariant
    from rootProject.file('common/src/main/resources')
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
