package net.minecraft.references;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.block.ColorCollection;

public class BlockIds {
   public static final ResourceKey ATTACHED_PUMPKIN_STEM = create("attached_pumpkin_stem");
   public static final ResourceKey ATTACHED_MELON_STEM = create("attached_melon_stem");
   public static final ResourceKey WATER = create("water");
   public static final ResourceKey LAVA = create("lava");
   public static final ResourceKey TALL_SEAGRASS = create("tall_seagrass");
   public static final ResourceKey PISTON_HEAD = create("piston_head");
   public static final ResourceKey MOVING_PISTON = create("moving_piston");
   public static final ResourceKey WALL_TORCH = create("wall_torch");
   public static final ResourceKey FIRE = create("fire");
   public static final ResourceKey SOUL_FIRE = create("soul_fire");
   public static final ResourceKey OAK_WALL_SIGN = create("oak_wall_sign");
   public static final ResourceKey SPRUCE_WALL_SIGN = create("spruce_wall_sign");
   public static final ResourceKey BIRCH_WALL_SIGN = create("birch_wall_sign");
   public static final ResourceKey ACACIA_WALL_SIGN = create("acacia_wall_sign");
   public static final ResourceKey CHERRY_WALL_SIGN = create("cherry_wall_sign");
   public static final ResourceKey JUNGLE_WALL_SIGN = create("jungle_wall_sign");
   public static final ResourceKey DARK_OAK_WALL_SIGN = create("dark_oak_wall_sign");
   public static final ResourceKey PALE_OAK_WALL_SIGN = create("pale_oak_wall_sign");
   public static final ResourceKey MANGROVE_WALL_SIGN = create("mangrove_wall_sign");
   public static final ResourceKey POPLAR_WALL_SIGN = create("poplar_wall_sign");
   public static final ResourceKey BAMBOO_WALL_SIGN = create("bamboo_wall_sign");
   public static final ResourceKey OAK_WALL_HANGING_SIGN = create("oak_wall_hanging_sign");
   public static final ResourceKey SPRUCE_WALL_HANGING_SIGN = create("spruce_wall_hanging_sign");
   public static final ResourceKey BIRCH_WALL_HANGING_SIGN = create("birch_wall_hanging_sign");
   public static final ResourceKey ACACIA_WALL_HANGING_SIGN = create("acacia_wall_hanging_sign");
   public static final ResourceKey CHERRY_WALL_HANGING_SIGN = create("cherry_wall_hanging_sign");
   public static final ResourceKey JUNGLE_WALL_HANGING_SIGN = create("jungle_wall_hanging_sign");
   public static final ResourceKey DARK_OAK_WALL_HANGING_SIGN = create("dark_oak_wall_hanging_sign");
   public static final ResourceKey PALE_OAK_WALL_HANGING_SIGN = create("pale_oak_wall_hanging_sign");
   public static final ResourceKey MANGROVE_WALL_HANGING_SIGN = create("mangrove_wall_hanging_sign");
   public static final ResourceKey POPLAR_WALL_HANGING_SIGN = create("poplar_wall_hanging_sign");
   public static final ResourceKey CRIMSON_WALL_HANGING_SIGN = create("crimson_wall_hanging_sign");
   public static final ResourceKey WARPED_WALL_HANGING_SIGN = create("warped_wall_hanging_sign");
   public static final ResourceKey BAMBOO_WALL_HANGING_SIGN = create("bamboo_wall_hanging_sign");
   public static final ResourceKey REDSTONE_WALL_TORCH = create("redstone_wall_torch");
   public static final ResourceKey SOUL_WALL_TORCH = create("soul_wall_torch");
   public static final ResourceKey COPPER_WALL_TORCH = create("copper_wall_torch");
   public static final ResourceKey NETHER_PORTAL = create("nether_portal");
   public static final ResourceKey WATER_CAULDRON = create("water_cauldron");
   public static final ResourceKey LAVA_CAULDRON = create("lava_cauldron");
   public static final ResourceKey POWDER_SNOW_CAULDRON = create("powder_snow_cauldron");
   public static final ResourceKey END_PORTAL = create("end_portal");
   public static final ResourceKey POTTED_TORCHFLOWER = create("potted_torchflower");
   public static final ResourceKey POTTED_OAK_SAPLING = create("potted_oak_sapling");
   public static final ResourceKey POTTED_SPRUCE_SAPLING = create("potted_spruce_sapling");
   public static final ResourceKey POTTED_BIRCH_SAPLING = create("potted_birch_sapling");
   public static final ResourceKey POTTED_JUNGLE_SAPLING = create("potted_jungle_sapling");
   public static final ResourceKey POTTED_ACACIA_SAPLING = create("potted_acacia_sapling");
   public static final ResourceKey POTTED_CHERRY_SAPLING = create("potted_cherry_sapling");
   public static final ResourceKey POTTED_DARK_OAK_SAPLING = create("potted_dark_oak_sapling");
   public static final ResourceKey POTTED_PALE_OAK_SAPLING = create("potted_pale_oak_sapling");
   public static final ResourceKey POTTED_MANGROVE_PROPAGULE = create("potted_mangrove_propagule");
   public static final ResourceKey POTTED_POPLAR_SAPLING = create("potted_poplar_sapling");
   public static final ResourceKey POTTED_FERN = create("potted_fern");
   public static final ResourceKey POTTED_DANDELION = create("potted_dandelion");
   public static final ResourceKey POTTED_GOLDEN_DANDELION = create("potted_golden_dandelion");
   public static final ResourceKey POTTED_POPPY = create("potted_poppy");
   public static final ResourceKey POTTED_BLUE_ORCHID = create("potted_blue_orchid");
   public static final ResourceKey POTTED_ALLIUM = create("potted_allium");
   public static final ResourceKey POTTED_AZURE_BLUET = create("potted_azure_bluet");
   public static final ResourceKey POTTED_RED_TULIP = create("potted_red_tulip");
   public static final ResourceKey POTTED_ORANGE_TULIP = create("potted_orange_tulip");
   public static final ResourceKey POTTED_WHITE_TULIP = create("potted_white_tulip");
   public static final ResourceKey POTTED_PINK_TULIP = create("potted_pink_tulip");
   public static final ResourceKey POTTED_OXEYE_DAISY = create("potted_oxeye_daisy");
   public static final ResourceKey POTTED_CORNFLOWER = create("potted_cornflower");
   public static final ResourceKey POTTED_LILY_OF_THE_VALLEY = create("potted_lily_of_the_valley");
   public static final ResourceKey POTTED_WITHER_ROSE = create("potted_wither_rose");
   public static final ResourceKey POTTED_RED_MUSHROOM = create("potted_red_mushroom");
   public static final ResourceKey POTTED_BROWN_MUSHROOM = create("potted_brown_mushroom");
   public static final ResourceKey POTTED_DEAD_BUSH = create("potted_dead_bush");
   public static final ResourceKey POTTED_CACTUS = create("potted_cactus");
   public static final ResourceKey SKELETON_WALL_SKULL = create("skeleton_wall_skull");
   public static final ResourceKey WITHER_SKELETON_WALL_SKULL = create("wither_skeleton_wall_skull");
   public static final ResourceKey ZOMBIE_WALL_HEAD = create("zombie_wall_head");
   public static final ResourceKey PLAYER_WALL_HEAD = create("player_wall_head");
   public static final ResourceKey CREEPER_WALL_HEAD = create("creeper_wall_head");
   public static final ResourceKey DRAGON_WALL_HEAD = create("dragon_wall_head");
   public static final ResourceKey PIGLIN_WALL_HEAD = create("piglin_wall_head");
   public static final ResourceKey END_GATEWAY = create("end_gateway");
   public static final ResourceKey FROSTED_ICE = create("frosted_ice");
   public static final ResourceKey KELP_PLANT = create("kelp_plant");
   public static final ResourceKey DEAD_TUBE_CORAL_WALL_FAN = create("dead_tube_coral_wall_fan");
   public static final ResourceKey DEAD_BRAIN_CORAL_WALL_FAN = create("dead_brain_coral_wall_fan");
   public static final ResourceKey DEAD_BUBBLE_CORAL_WALL_FAN = create("dead_bubble_coral_wall_fan");
   public static final ResourceKey DEAD_FIRE_CORAL_WALL_FAN = create("dead_fire_coral_wall_fan");
   public static final ResourceKey DEAD_HORN_CORAL_WALL_FAN = create("dead_horn_coral_wall_fan");
   public static final ResourceKey TUBE_CORAL_WALL_FAN = create("tube_coral_wall_fan");
   public static final ResourceKey BRAIN_CORAL_WALL_FAN = create("brain_coral_wall_fan");
   public static final ResourceKey BUBBLE_CORAL_WALL_FAN = create("bubble_coral_wall_fan");
   public static final ResourceKey FIRE_CORAL_WALL_FAN = create("fire_coral_wall_fan");
   public static final ResourceKey HORN_CORAL_WALL_FAN = create("horn_coral_wall_fan");
   public static final ResourceKey BAMBOO_SAPLING = create("bamboo_sapling");
   public static final ResourceKey POTTED_BAMBOO = create("potted_bamboo");
   public static final ResourceKey VOID_AIR = create("void_air");
   public static final ResourceKey CAVE_AIR = create("cave_air");
   public static final ResourceKey BUBBLE_COLUMN = create("bubble_column");
   public static final ResourceKey WEEPING_VINES_PLANT = create("weeping_vines_plant");
   public static final ResourceKey TWISTING_VINES_PLANT = create("twisting_vines_plant");
   public static final ResourceKey CRIMSON_WALL_SIGN = create("crimson_wall_sign");
   public static final ResourceKey WARPED_WALL_SIGN = create("warped_wall_sign");
   public static final ResourceKey POTTED_CRIMSON_FUNGUS = create("potted_crimson_fungus");
   public static final ResourceKey POTTED_WARPED_FUNGUS = create("potted_warped_fungus");
   public static final ResourceKey POTTED_CRIMSON_ROOTS = create("potted_crimson_roots");
   public static final ResourceKey POTTED_WARPED_ROOTS = create("potted_warped_roots");
   public static final ResourceKey CANDLE_CAKE = create("candle_cake");
   public static final ResourceKey CAVE_VINES_PLANT = create("cave_vines_plant");
   public static final ResourceKey BIG_DRIPLEAF_STEM = create("big_dripleaf_stem");
   public static final ResourceKey POTTED_AZALEA_BUSH = create("potted_azalea_bush");
   public static final ResourceKey POTTED_FLOWERING_AZALEA_BUSH = create("potted_flowering_azalea_bush");
   public static final ResourceKey POTTED_OPEN_EYEBLOSSOM = create("potted_open_eyeblossom");
   public static final ResourceKey POTTED_CLOSED_EYEBLOSSOM = create("potted_closed_eyeblossom");
   public static final ColorCollection WALL_BANNER = createSimpleColored("wall_banner");
   public static final ColorCollection DYED_CANDLE_CAKE = createSimpleColored("candle_cake");

   private static ResourceKey create(final String name) {
      return ResourceKey.create(Registries.BLOCK, Identifier.withDefaultNamespace(name));
   }

   private static ColorCollection createSimpleColored(final String baseName) {
      return ColorCollection.prefixWithColor(ColorCollection.create(baseName)).map(BlockIds::create);
   }
}
