package com.kingodogo.buildscape.recipe.framework.compiler;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;

public final class BundledRecipeCacheVerify {
    public static void main(String[] args) throws Exception {
        if (args.length != 2) {
            throw new IllegalArgumentException("Expected source directory and bundled cache paths");
        }
        byte[] generated = RecipeCacheGenerator.generateCache(Path.of(args[0]));
        Path bundled = Path.of(args[1]);
        if (!Files.isRegularFile(bundled) || !Arrays.equals(generated, Files.readAllBytes(bundled))) {
            throw new IllegalStateException("Bundled recipe cache differs from generated bytes; run syncBundledRecipeCache");
        }
        System.out.println("Bundled recipe cache verified byte-for-byte: " + bundled);
    }
}
